### PR TITLE
Take a look anyway: you've done most of this already

### PR DESCRIPTION
**Pull request by mattgodbolt**
I'll separate out the CPUID serializing as a new PR on the master. Then there's nothing really here to merge; but I thought I'd give you a chuckle as to us finding the same issue at the same time!

### CODE REVIEW

**Comment by mattgodbolt** [comment]
actually; this branch has one useful thing: really we should use the counter number from the mmap'd region instead of the hardcoded 0. I'll send a PR for that too.

**Comment by rmmh** [comment]
this PR appears to be reversed?

**Comment by mattgodbolt** [comment]
Ah could be. I tied myself in git knots a little in trying to separate
everything cleanly but still keep my own 'master'. Sorry!

**Comment by mattgodbolt** [comment]
Closing as I suspect fixing it up is not worthwhile! Sorry for the trouble

**Pull request closed without merging**
